import {StyleSheet, Dimensions} from 'react-native';
import {GestureHandlerRootView} from 'react-native-gesture-handler';
import {APP_COLORS} from '../../shared/styles/colors';

export default StyleSheet.create({
  rootContainer: {
    backgroundColor: 'white',
    flex: 1,
  },
  container: {
    flex: 1,
  },
  card: {
    backgroundColor: 'rgba(46, 46, 46, 0.8)',
    width: Dimensions.get('window').width - 40,
    flex: 0.8,
    marginHorizontal: 20,
    marginBottom: 20,
    padding: 20,
    borderRadius: 20,

    shadowColor: '#FFF',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  bubble: {
    backgroundColor: '#1d54d6',
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'baseline',
    marginHorizontal: 5,
  },
  bubbleGrey: {
    backgroundColor: '#737373',
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'baseline',
    marginHorizontal: 5,
  },
  titleText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 13,
  },
  textInput: {
    backgroundColor: '#4F4F4F',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 17,
    marginTop: 5,
    marginBottom: 20,

    shadowColor: '#FFF',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 5,
  },
  inputTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFF',
    marginLeft: 5,
    marginTop: 20,
  },
  roundedOuter: {
    shadowColor: '#FC466B',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  roundedButton: {
    backgroundColor: '#000',
    borderRadius: 10,
    paddingVertical: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
  },
  buttonText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 18,
  },
  logoText: {
    fontWeight: 'bold',
    fontSize: 25,
    color: '#F0F0F0',
    marginVertical: 5,
    marginHorizontal: 5,
    zIndex: 999,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 5,
  },
  welcome: {
    fontWeight: 'bold',
    fontSize: 50,
    color: '#F0F0F0',
    marginVertical: 20,
    marginHorizontal: 20,
    zIndex: 999,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 5,
  },
  topImage: {
    position: 'absolute',
    top: -40,
    right: -60,
    width: 400,
    height: 400,
    opacity: 0.35,
  },
  logo: {
    width: 30,
    height: 30,
    marginLeft: 20,
  },
  generatedText: {
    fontWeight: 'bold',
    fontSize: 25,
    marginTop: 10,
    color: '#323232',
  },
  urlView: {
    color: '#000',
    borderRadius: 10,
    fontSize: 22,
    backgroundColor: '#FFF',
    width: '90%',
    marginTop: 70,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
});
